/*
 * @name    : Pokémon Idle - 汉化词典
 * @game    : pkmn-idle.com
 * @framework: 锅巴汉化 V0.8.2
 * @total   : 1332 translations
 */

// ============================================================
// 匹配配置
// ============================================================
var cnConfig = {
    ignoreCase: true,
    trimSpaces: true,
};

// ============================================================
// cnCategoriesList — 分类名称注册表
// ============================================================
var cnCategoriesList = [
    "pokemon",
    "move",
    "type",
    "location",
    "trainer",
    "badge",
    "item",
];

// ============================================================
// cnItems — 翻译词条
// ============================================================
var cnItems = {
    'Bulbasaur': '妙蛙种子',
    'Ivysaur': '妙蛙草',
    'Venusaur': '妙蛙花',
    'Charmander': '小火龙',
    'Charmeleon': '火恐龙',
    'Charizard': '喷火龙',
    'Squirtle': '杰尼龟',
    'Wartortle': '卡咪龟',
    'Blastoise': '水箭龟',
    'Caterpie': '绿毛虫',
    'Metapod': '铁甲蛹',
    'Butterfree': '巴大蝶',
    'Weedle': '独角虫',
    'Kakuna': '铁壳蛹',
    'Beedrill': '大针蜂',
    'Pidgey': '波波',
    'Pidgeotto': '比比鸟',
    'Pidgeot': '大比鸟',
    'Rattata': '小拉达',
    'Raticate': '拉达',
    'Spearow': '烈雀',
    'Fearow': '大嘴雀',
    'Ekans': '阿柏蛇',
    'Arbok': '阿柏怪',
    'Pikachu': '皮卡丘',
    'Raichu': '雷丘',
    'Sandshrew': '穿山鼠',
    'Sandslash': '穿山王',
    'Nidoran♀': '尼多兰',
    'Nidorina': '尼多娜',
    'Nidoqueen': '尼多后',
    'Nidoran♂': '尼多朗',
    'Nidorino': '尼多力诺',
    'Nidoking': '尼多王',
    'Clefairy': '皮皮',
    'Clefable': '皮可西',
    'Vulpix': '六尾',
    'Ninetales': '九尾',
    'Jigglypuff': '胖丁',
    'Wigglytuff': '胖可丁',
    'Zubat': '超音蝠',
    'Golbat': '大嘴蝠',
    'Oddish': '走路草',
    'Gloom': '臭臭花',
    'Vileplume': '霸王花',
    'Paras': '派拉斯',
    'Parasect': '派拉斯特',
    'Venonat': '毛球',
    'Venomoth': '末入蛾',
    'Diglett': '地鼠',
    'Dugtrio': '三地鼠',
    'Meowth': '喵喵',
    'Persian': '猫老大',
    'Psyduck': '可达鸭',
    'Golduck': '哥达鸭',
    'Mankey': '猴怪',
    'Primeape': '火爆猴',
    'Growlithe': '卡蒂狗',
    'Arcanine': '风速狗',
    'Poliwag': '蚊香蝌蚪',
    'Poliwhirl': '蚊香君',
    'Poliwrath': '蚊香泳士',
    'Abra': '凯西',
    'Kadabra': '勇基拉',
    'Alakazam': '胡地',
    'Machop': '腕力',
    'Machoke': '豪力',
    'Machamp': '怪力',
    'Bellsprout': '喇叭芽',
    'Weepinbell': '口呆花',
    'Victreebel': '大食花',
    'Tentacool': '玛瑙水母',
    'Tentacruel': '毒刺水母',
    'Geodude': '小拳石',
    'Graveler': '隆隆石',
    'Golem': '隆隆岩',
    'Ponyta': '小火马',
    'Rapidash': '烈焰马',
    'Slowpoke': '呆呆兽',
    'Slowbro': '呆壳兽',
    'Magnemite': '小磁怪',
    'Magneton': '三合一磁怪',
    'Farfetch\'d': '大葱鸭',
    'Doduo': '嘟嘟',
    'Dodrio': '嘟嘟利',
    'Seel': '小海狮',
    'Dewgong': '白海狮',
    'Grimer': '臭泥',
    'Muk': '臭臭泥',
    'Shellder': '大舌贝',
    'Cloyster': '刺甲贝',
    'Gastly': '鬼斯',
    'Haunter': '鬼斯通',
    'Gengar': '耿鬼',
    'Onix': '大岩蛇',
    'Drowzee': '催眠貘',
    'Hypno': '引梦貘人',
    'Krabby': '大钳蟹',
    'Kingler': '巨钳蟹',
    'Voltorb': '霹雳电球',
    'Electrode': '顽皮雷弹',
    'Exeggcute': '蛋蛋',
    'Exeggutor': '椰蛋树',
    'Cubone': '卡拉卡拉',
    'Marowak': '嘎啦嘎啦',
    'Hitmonlee': '沙瓦郎',
    'Hitmonchan': '艾比郎',
    'Lickitung': '大舌头',
    'Koffing': '瓦斯弹',
    'Weezing': '双弹瓦斯',
    'Rhyhorn': '铁甲犀牛',
    'Rhydon': '铁甲暴龙',
    'Chansey': '吉利蛋',
    'Tangela': '蔓藤怪',
    'Kangaskhan': '袋兽',
    'Horsea': '墨海马',
    'Seadra': '海刺龙',
    'Goldeen': '角金鱼',
    'Seaking': '金鱼王',
    'Staryu': '海星星',
    'Starmie': '宝石海星',
    'Mr. Mime': '魔墙人偶',
    'Scyther': '飞天螳螂',
    'Jynx': '迷唇姐',
    'Electabuzz': '电击兽',
    'Magmar': '鸭嘴火兽',
    'Pinsir': '凯罗斯',
    'Tauros': '肯泰罗',
    'Magikarp': '鲤鱼王',
    'Gyarados': '暴鲤龙',
    'Lapras': '拉普拉斯',
    'Ditto': '百变怪',
    'Eevee': '伊布',
    'Vaporeon': '水伊布',
    'Jolteon': '雷伊布',
    'Flareon': '火伊布',
    'Porygon': '多边兽',
    'Omanyte': '菊石兽',
    'Omastar': '多刺菊石兽',
    'Kabuto': '化石盔',
    'Kabutops': '镰刀盔',
    'Aerodactyl': '化石翼龙',
    'Snorlax': '卡比兽',
    'Articuno': '急冻鸟',
    'Zapdos': '闪电鸟',
    'Moltres': '火焰鸟',
    'Dratini': '迷你龙',
    'Dragonair': '哈克龙',
    'Dragonite': '快龙',
    'Mewtwo': '超梦',
    'Mew': '梦幻',
    'Absorb': '吸取',
    'Acid': '溶解液',
    'Air Cutter': '空气利刃',
    'Amnesia': '瞬间失忆',
    'Ancient Power': '原始之力',
    'Aurora Beam': '极光束',
    'Barrier': '屏障',
    'Bind': '绑紧',
    'Bite': '咬住',
    'Blizzard': '暴风雪',
    'Body Slam': '泰山压顶',
    'Bone Club': '骨棒',
    'Bonemerang': '骨棒回力镖',
    'Bubble': '泡沫',
    'Bubble Beam': '泡沫光线',
    'Bug Bite': '虫咬',
    'Clamp': '贝壳夹',
    'Comet Punch': '连续拳',
    'Confuse Ray': '奇异之光',
    'Confusion': '念力',
    'Conversion': '纹理',
    'Counter': '双倍奉还',
    'Cross Chop': '十字劈',
    'Crunch': '咬碎',
    'Defense Curl': '变圆',
    'Dig': '挖洞',
    'Disable': '定身法',
    'Disarming Voice': '妖精之风',
    'Double Kick': '二连踢',
    'Double Slap': '连环巴掌',
    'Dragon Breath': '龙息',
    'Dragon Claw': '龙爪',
    'Dragon Rage': '龙之怒',
    'Dream Eater': '食梦',
    'Drill Peck': '钻孔啄',
    'Earthquake': '地震',
    'Ember': '火花',
    'Fire Blast': '大字爆炎',
    'Fire Punch': '火焰拳',
    'Fire Spin': '火焰旋涡',
    'Flame Wheel': '火焰轮',
    'Flamethrower': '喷射火焰',
    'Focus Energy': '聚气',
    'Fury Attack': '乱击',
    'Fury Swipes': '乱抓',
    'Glare': '大蛇瞪眼',
    'Growl': '叫声',
    'Gust': '起风',
    'Harden': '变硬',
    'Headbutt': '头锤',
    'High Jump Kick': '飞膝踢',
    'Horn Attack': '角撞',
    'Hydro Pump': '水炮',
    'Hyper Beam': '破坏光线',
    'Hyper Fang': '必杀门牙',
    'Hypnosis': '催眠术',
    'Ice Beam': '冷冻光束',
    'Ice Punch': '冷冻拳',
    'Icicle Crash': '冰柱坠落',
    'Icy Wind': '冰冻之风',
    'Karate Chop': '空手劈',
    'Leech Life': '吸血',
    'Leech Seed': '寄生种子',
    'Leer': '瞪眼',
    'Light Screen': '光墙',
    'Low Kick': '踢倒',
    'Magnitude': '震级',
    'Mega Kick': '百万吨踢击',
    'Mega Punch': '百万吨拳击',
    'Megahorn': '超级角击',
    'Metal Claw': '金属爪',
    'Mirror Move': '鹦鹉学舌',
    'Outrage': '逆鳞',
    'Peck': '啄',
    'Perish Song': '灭亡之歌',
    'Petal Dance': '花瓣舞',
    'Pin Missile': '飞弹针',
    'Poison Powder': '毒粉',
    'Poison Sting': '毒针',
    'Pound': '拍击',
    'Psybeam': '幻象光线',
    'Psychic': '超能力者',
    'Quick Attack': '电光一闪',
    'Rage': '愤怒',
    'Razor Leaf': '飞叶快刀',
    'Reflect': '反射壁',
    'Rest': '睡觉',
    'Rock Slide': '岩崩',
    'Rock Throw': '落石',
    'Rollout': '滚动',
    'Sand Attack': '泼沙',
    'Sandstorm': '沙暴',
    'Scratch': '抓',
    'Seismic Toss': '地球上投',
    'Self-Destruct': '自爆',
    'Shadow Ball': '暗影球',
    'Sharpen': '棱角化',
    'Signal Beam': '信号光束',
    'Sing': '唱歌',
    'Sky Attack': '神鸟猛击',
    'Slam': '摔打',
    'Slash': '劈开',
    'Sleep Powder': '催眠粉',
    'Sludge': '污泥攻击',
    'Sludge Bomb': '污泥炸弹',
    'Smokescreen': '烟幕',
    'Snore': '打鼾',
    'Sonic Boom': '音爆',
    'Splash': '水溅跃',
    'Stomp': '踩踏',
    'String Shot': '吐丝',
    'Submission': '地狱翻滚',
    'Supersonic': '超音波',
    'Surf': '冲浪',
    'Swift': '高速星星',
    'Swords Dance': '剑舞',
    'Tackle': '撞击',
    'Tail Whip': '摇尾巴',
    'Take Down': '猛撞',
    'Teleport': '瞬间移动',
    'Thunder Punch': '雷电拳',
    'Thunder Shock': '电击',
    'Thunder Wave': '电磁波',
    'Thunderbolt': '十万伏特',
    'Toxic': '剧毒',
    'Tri Attack': '三重攻击',
    'Vine Whip': '藤鞭',
    'Water Gun': '水枪',
    'Water Pulse': '水之波动',
    'Wing Attack': '翅膀攻击',
    'Wrap': '缠绕',
    'Normal': '一般',
    'Fire': '火',
    'Water': '水',
    'Electric': '电',
    'Grass': '草',
    'Ice': '冰',
    'Fighting': '格斗',
    'Poison': '中毒',
    'Ground': '地面',
    'Flying': '飞行',
    'Bug': '虫',
    'Rock': '岩石',
    'Ghost': '幽灵',
    'Dragon': '龙',
    'Dark': '恶',
    'Steel': '钢',
    'Fairy': '妖精',
    'Pallet Town': '真新镇',
    'Viridian City': '常青市',
    'Pewter City': '深灰市',
    'Cerulean City': '华蓝市',
    'Vermilion City': '枯叶市',
    'Lavender Town': '紫苑镇',
    'Celadon City': '彩虹市',
    'Fuchsia City': '浅红市',
    'Saffron City': '金黄市',
    'Cinnabar Island': '红莲岛',
    'Indigo Plateau': '石英高原',
    'Cerulean Cave': '华蓝洞窟',
    'Diglett\'s Cave': '地鼠洞窟',
    'Mt. Moon': '月见山',
    'Pokemon Mansion': '宝可梦大宅',
    'Pokemon Tower': '宝可梦塔',
    'Power Plant': '无人发电厂',
    'Rock Tunnel': '岩山隧道',
    'Safari Zone': '狩猎地带',
    'Seafoam Islands': '双子岛',
    'Victory Road': '冠军之路',
    'Viridian Forest': '常青森林',
    'Raid Island': '团体战岛',
    'Nugget Bridge': '金珠大桥',
    'Celadon Dept. Store': '彩虹百货公司',
    'Route 1': '1号道路',
    'Route 2': '2号道路',
    'Route 3': '3号道路',
    'Route 4': '4号道路',
    'Route 5': '5号道路',
    'Route 6': '6号道路',
    'Route 7': '7号道路',
    'Route 8': '8号道路',
    'Route 9': '9号道路',
    'Route 10': '10号道路',
    'Route 11': '11号道路',
    'Route 12': '12号道路',
    'Route 13': '13号道路',
    'Route 14': '14号道路',
    'Route 15': '15号道路',
    'Route 16': '16号道路',
    'Route 17': '17号道路',
    'Route 18': '18号道路',
    'Route 19': '19号道路',
    'Route 20': '20号道路',
    'Route 21': '21号道路',
    'Route 22': '22号道路',
    'Route 23': '23号道路',
    'Route 24': '24号道路',
    'Route 25': '25号道路',
    'Cerulean Mart': '华蓝商店',
    'Cinnabar Mart': '红莲商店',
    'Fuchsia Mart': '浅红商店',
    'Indigo Plateau Mart': '石英高原商店',
    'Lavender Mart': '紫苑商店',
    'Pewter Mart': '深灰商店',
    'Saffron Mart': '金黄商店',
    'Vermilion Mart': '枯叶商店',
    'Viridian Mart': '常青商店',
    'Pewter City Gym Leader': '深灰市道馆馆主',
    'Cerulean City Gym Leader': '华蓝市道馆馆主',
    'Vermilion City Gym Leader': '枯叶市道馆馆主',
    'Celadon City Gym Leader': '彩虹市道馆馆主',
    'Fuchsia City Gym Leader': '浅红市道馆馆主',
    'Saffron City Gym Leader': '金黄市道馆馆主',
    'Cinnabar Island Gym Leader': '红莲岛道馆馆主',
    'Viridian City Gym Leader': '常青市道馆馆主',
    'Brock': '小刚',
    'Misty': '小霞',
    'Lt. Surge': '马志士',
    'Erika': '莉佳',
    'Koga': '阿桔',
    'Sabrina': '娜姿',
    'Blaine': '夏伯',
    'Giovanni': '坂木',
    'Lorelei': '科拿',
    'Bruno': '希巴',
    'Agatha': '菊子',
    'Lance': '渡',
    'Blue': '青绿',
    'Ace Trainer Chloe': '精英训练师 克洛伊',
    'Ace Trainer Jason': '精英训练师 杰森',
    'Ace Trainer Lauren': '精英训练师 劳伦',
    'Beauty Bridget': '大姐姐 布里奇特',
    'Beauty Lola': '大姐姐 萝拉',
    'Beauty Tamia': '大姐姐 塔米娅',
    'Bug Catcher Doug': '捕虫少年 道格',
    'Bug Catcher Rick': '捕虫少年 瑞克',
    'Camper Jeff': '露营少年 杰夫',
    'Camper Lola': '露营少女 萝拉',
    'Channeler Carly': '祈祷师 卡莉',
    'Channeler Hope': '祈祷师 霍普',
    'Channeler Laurel': '祈祷师 劳雷尔',
    'Channeler Patricia': '祈祷师 帕特丽夏',
    'CoolTrainer Alexa': 'CoolTrainer 亚历克莎',
    'CoolTrainer Grayson': 'CoolTrainer 格雷森',
    'CoolTrainer Naomi': 'CoolTrainer 娜奥米',
    'CoolTrainer Samuel': 'CoolTrainer 塞缪尔',
    'CoolTrainer Vincent': 'CoolTrainer 文森特',
    'Gentleman Arthur': '绅士 亚瑟',
    'Gentleman Brooks': '绅士 布鲁克斯',
    'Hiker Franklin': '登山男 富兰克林',
    'Hiker Liam': '登山男 利亚姆',
    'Hiker Marcos': '登山男 马科斯',
    'Juggler Dalton': '杂耍艺人 道尔顿',
    'Juggler Nelson': '杂耍艺人 尼尔森',
    'Lass Robin': '迷你裙 罗宾',
    'Lass Sally': '迷你裙 莎莉',
    'Psychic Cameron': '超能力者 卡梅隆',
    'Psychic Johan': '超能力者 约翰',
    'Psychic Tyron': '超能力者 泰伦',
    'Sailor Dylan': '水手 迪伦',
    'Sailor Eddie': '水手 埃迪',
    'Sailor Huey': '水手 休伊',
    'Scientist Beau': '研究员 博',
    'Scientist Connor': '研究员 康纳',
    'Scientist Ivan': '研究员 伊万',
    'Scientist Taylor': '研究员 泰勒',
    'Scientist Ted': '研究员 泰德',
    'Super Nerd Derek': '理科男 德里克',
    'Super Nerd Zack': '理科男 扎克',
    'Swimmer Diana': '泳裤少女 戴安娜',
    'Swimmer Luis': '泳裤少年 路易斯',
    'Swimmer Tara': '泳裤少女 塔拉',
    'Tamer Edgar': '驯兽师 埃德加',
    'Tamer Phil': '驯兽师 菲尔',
    'Tamer Vincent': '驯兽师 文森特',
    'Youngster Ben': '短裤少年 本',
    'Youngster Joey': '短裤少年 乔伊',
    'Boulder Badge': '灰色徽章',
    'Cascade Badge': '蓝色徽章',
    'Thunder Badge': '橙色徽章',
    'Rainbow Badge': '彩虹徽章',
    'Soul Badge': '粉色徽章',
    'Marsh Badge': '金色徽章',
    'Volcano Badge': '深红徽章',
    'Earth Badge': '绿色徽章',
    'Poke Ball': '精灵球',
    'Poke Balls': '精灵球',
    'Great Ball': '超级球',
    'Ultra Ball': '高级球',
    'Master Ball': '大师球',
    'Fire Stone': '火之石',
    'Water Stone': '水之石',
    'Thunder Stone': '雷之石',
    'Leaf Stone': '叶之石',
    'Moon Stone': '月之石',
    'Link Cable': '连接线',
    'Exp. Share': '学习装置',
    'Shiny Charm': '闪耀护符',
    'Honey': '甜甜蜜',
    'Repel': '除虫喷雾',
    'HP': '生命',
    'Attack': '攻击',
    'Defense': '防御',
    'Speed': '速度',
    'Sp. Atk': '特攻',
    'Sp. Def': '特防',
    'SpA': '特攻',
    'SpD': '特防',
    'Pokemon Idle v': '宝可梦放置 v',
    'Pokemon': '宝可梦',
    'Pokémon Idle': '宝可梦放置',
    'Choose Your Starter!': '选择你的初始宝可梦！',
    'Choose!': '选择！',
    'Activity': '活动',
    'Patch Notes': '补丁说明',
    'View Patch Notes': '查看补丁说明',
    'TOWN MAP': '城镇地图',
    'TRAVEL': '旅行',
    'Party': '同行',
    'Box': '盒子',
    'Moves': '招式',
    'Items': '道具',
    'Badges': '徽章',
    'Settings': '设置',
    'Info': '信息',
    'Pokedex': '宝可梦图鉴',
    'Pokedex New': '图鉴新',
    'Location': '地点',
    'Gym Leaders': '道馆馆主',
    'Elite Four': '四天王',
    'Gyms': '道馆',
    'Home': '家',
    'Town': '城镇',
    'Route': '道路',
    'Reward Shop': '奖励商店',
    'Battle Log': '战斗日志',
    'Catch Mode': '捕捉模式',
    'Catch Settings': '捕捉设置',
    'IV Assignment': '个体值分配',
    'Manage Moves': '管理招式',
    'Available Moves': '可学招式',
    'Current Moves (': '当前招式（',
    'Move to Party': '移动到同行',
    'Send to Box': '放入盒子',
    'Release': '放生',
    'Legendary Raid': '传说团体战',
    'Legendary Raid System': '传说团体战系统',
    'Leave Raid': '离开团体战',
    'Mobile Layout': '移动端布局',
    'Quality of Life': '生活品质',
    'New Content': '新内容',
    'Smarter AI': '更聪明的AI',
    'FIGHT': '战斗',
    'CATCH': '捕捉',
    'EVOLVE': '进化',
    'HEAL': '恢复',
    'MOVES': '招式',
    'LOCKED': '未解锁',
    'Locked': '未解锁',
    'BEGIN CHALLENGE': '开始挑战',
    'SKIP': '跳过',
    'INPUT': '输入',
    'Confirm': '确认',
    'Cancel': '取消',
    'Clear': '清除',
    'Ready': '就绪',
    'Pause': '暂停',
    'Save': '保存',
    'Load': '读取',
    'Sort': '排序',
    'Catch': '捕捉',
    'Capture': '捕获',
    'Buy': '购买',
    'Escape': '逃跑',
    'Got it!': '知道了！',
    'Yes, Reset': '是的，重置',
    'Reset Save Data': '重置存档',
    'Wild Pokemon': '野生宝可梦',
    'Trainer battles': '训练师战斗',
    'Battle scene scales to fit the screen width': '战斗场景自适应屏幕宽度',
    'Battle log auto-hides when space is too tight': '空间不足时战斗日志自动隐藏',
    'A critical hit!': '命中要害！',
    'It\'s super effective!': '效果拔群！',
    'It\'s not very effective...': '效果不理想…',
    'It had no effect!': '没有效果！',
    'No Poke Balls left!': '没有精灵球了！',
    'No items.': '没有道具。',
    'Looking for trainers...': '正在寻找训练师…',
    'Beat Champion': '击败冠军',
    'Earned a Victory Token!': '获得了胜利徽章！',
    'Game loaded!': '游戏加载完成！',
    'ATK:': '攻击：',
    'DEF:': '防御：',
    'SP.A:': '特攻：',
    'SP.D:': '特防：',
    'SPD:': '速度：',
    'HP:': '生命：',
    'Lv.': '等级',
    'Lv ??': '等级 ??',
    'EXP': '经验',
    'Ball:': '精灵球：',
    'Active:': '生效中：',
    'Owned:': '持有：',
    'Above level:': '等级以上：',
    'Not caught yet': '尚未捕捉',
    'Only if shiny': '仅闪光',
    'Always catch': '总是捕捉',
    'Catch all': '捕捉全部',
    'Always': '总是',
    'Never': '从不',
    'None': '无',
    'Common': '普通',
    'Uncommon': '少见',
    'Rare': '稀有',
    'Very Rare': '非常稀有',
    'Ultra Rare': '极度稀有',
    'Unidentified': '未识别',
    'Unknown location': '未知地点',
    'Healing your Pokemon...': '正在恢复你的宝可梦…',
    'Your Pokemon are fully healed!': '你的宝可梦已完全恢复！',
    'Your Pokemon were healed!': '你的宝可梦已恢复！',
    'Auto-Proceed': '自动前进',
    'Auto-proceed: ON': '自动前进：开',
    'Auto-proceed: OFF': '自动前进：关',
    'Next Unlock': '下一解锁',
    'Applying...': '正在使用…',
    'Shinies caught:': '已捕闪光：',
    'Shinies seen:': '已见闪光：',
    'Shiny odds: 1/': '闪光概率：1/',
    'Victory Tokens': '胜利徽章',
    'Victory Tokens:': '胜利徽章：',
    'Pokemon Idle subreddit': '宝可梦放置 Reddit 社区',
    'r/PkmnIdle': 'r/PkmnIdle',
    'Pokemon League Champion': '宝可梦联盟冠军',
    'Elite Four & Champion': '四天王 & 冠军',
    'Victory Tokens & Reward Shop': '胜利徽章 & 奖励商店',
    'Evolution Items & Item-Based Evolution': '进化道具 & 道具进化',
    'Gym Leaders, Elite Four & Champion': '道馆馆主、四天王 & 冠军',
    'Gym Leaders, Elite Four, Evolution Items & More': '道馆馆主、四天王、进化道具 & 更多',
    'Legendary Raids, Move Effects & Battle Balance': '传说团体战、招式效果 & 战斗平衡',
    'Repel & Honey Items': '除虫喷雾 & 甜甜蜜道具',
    'Repel & Honey, Exp. Share, Mobile Layout & QoL': '除虫喷雾 & 甜甜蜜、学习装置、移动端布局 & 生活品质',
    'Move Secondary Effects': '招式附加效果',
    'Stat Stage Moves': '能力阶段招式',
    'A quiet town where your journey begins.': '你旅程开始的一个宁静小镇。',
    'A city with a Pokemon Gym.': '一个有宝可梦道馆的城市。',
    'A dense forest full of bug Pokemon.': '充满虫属性宝可梦的茂密森林。',
    'A winding path leading to the forest.': '通往森林的蜿蜒小径。',
    'A rocky trail heading east.': '向东的岩石小径。',
    'A mountain trail leading to Cerulean.': '通往华蓝市的山路。',
    'A beautiful city with flowing water.': '有流水的美丽城市。',
    'A path south from Cerulean to Saffron.': '从华蓝市南下到金黄市的道路。',
    'A road east of Vermilion City.': '枯叶市东边的道路。',
    'A path through tall grass heading south.': '穿过高草丛向南的道路。',
    'A short path through tall grass.': '穿过高草丛的短途道路。',
    'A path leading south to the harbor city.': '通往南方港口城市的道路。',
    'A path connecting Saffron and Lavender.': '连接金黄市和紫苑镇的道路。',
    'A short road to Celadon City.': '通往彩虹市的短途道路。',
    'The start of Cycling Road heading south.': '单车路起点，向南延伸。',
    'The end of Cycling Road near Fuchsia.': '单车路终点，靠近浅红市。',
    'A sea route leading to the Seafoam Islands.': '通往双子岛的海路。',
    'A sea route back to Pallet Town.': '返回真新镇的海路。',
    'A rugged path through the mountains.': '穿越山脉的崎岖道路。',
    'A maze-like path heading west.': '向西的迷宫般道路。',
    'The road to the Pokemon League.': '通往宝可梦联盟的道路。',
    'The final challenge before the Elite Four.': '四天王前的最后挑战。',
    'A pitched-black cave you must navigate carefully.': '需要小心前行的漆黑洞窟。',
    'A tunnel dug by Diglett connecting two routes.': '地鼠挖出的连接两条道路的隧道。',
    'Icy caves home to legendary birds.': '传说鸟类的冰冻洞窟家园。',
    'Home to the Safari Zone and a ninja gym.': '狩猎地带和忍者道馆的所在地。',
    'A volcanic island with a research lab.': '有研究所的火山岛。',
    'Home of the Pokemon League.': '宝可梦联盟的所在地。',
    'A memorial tower haunted by ghosts.': '被幽灵萦绕的纪念塔。',
    'An abandoned plant crackling with electricity.': '一座噼啪作响的废弃发电厂。',
    'A cavern filled with rare fossils.': '充满稀有化石的洞穴。',
    'A burned-out mansion hiding dark secrets.': '隐藏着黑暗秘密的烧毁大宅。',
    'A mysterious cave with immensely powerful Pokemon.': '有极其强大宝可梦的神秘洞窟。',
    'A nature reserve with rare Pokemon.': '有稀有宝可梦的自然保护区。',
    'A bustling port city with electric gym.': '有电系道馆的繁华港口城市。',
    'A city of rainbow dreams and a large dept store.': '彩虹梦想之城和大型百货商店。',
    'The largest city in Kanto, home to Silph Co.': '关都最大的城市，西尔佛公司的所在地。',
    'A city known for its museum and gym.': '以博物馆和道馆闻名的城市。',
    'A cape where a famous collector lives.': '著名收藏家居住的海角。',
    'The final stretch to Fuchsia City.': '通往浅红市的最后一段路。',
    'A mysterious floating island where legendary Pokemon dwell.': '传说宝可梦栖息的神秘浮岛。',
    'Ocean waves south of Fuchsia City.': '浅红市以南的海浪。',
    'Nugget Bridge stretches to the north.': '金桥向北延伸。',
    'A path near the Power Plant.': '靠近发电厂的道路。',
    'A standard ball for catching Pokemon.': '用来捕捉宝可梦的标准球。',
    'A high-performance ball with a better catch rate.': '捕获率更高的高性能球。',
    'An ultra-performance ball with an even better catch rate.': '捕获率更高的超高性能球。',
    'The best ball that catches any Pokemon without fail.': '必定能捕捉任何宝可梦的最强球。',
    'Evolves certain Pokemon.': '使特定宝可梦进化。',
    'Evolves certain Fire-type Pokemon.': '使特定火属性宝可梦进化。',
    'Evolves certain Water-type Pokemon.': '使特定水属性宝可梦进化。',
    'Evolves certain Electric-type Pokemon.': '使特定电属性宝可梦进化。',
    'Evolves certain Grass-type Pokemon.': '使特定草属性宝可梦进化。',
    'Evolves Pokemon that normally evolve by trading.': '使通常通过通信交换进化的宝可梦进化。',
    'Doubles shiny encounter odds from 1/8192 to 1/4096': '将闪光遭遇概率从1/8192翻倍至1/4096',
    'Shares 5% EXP with each non-fainted party member for 1000 battles. Active Pokemon gets 50%.': '与每只非濒死队友分享5%经验值，持续1000场战斗。出战宝可梦获得50%。',
    'Doubles a wild Pokemon\'s encounter weight on the current route for 500 battles.': '在当前道路上使一只野生宝可梦的遭遇权重翻倍，持续500场战斗。',
    'Halves a wild Pokemon\'s encounter weight on the current route for 500 battles.': '在当前道路上使一只野生宝可梦的遭遇权重减半，持续500场战斗。',
    'Click on Route 1 to begin your pokemon adventure!': '点击1号道路开始你的宝可梦冒险！',
    'Click Raid Island to heal your party and fight a random legendary repeatedly until you wipe or leave': '点击团体战岛来恢复队伍并与随机传说宝可梦反复战斗，直到全灭或离开',
    'Legendaries will grow stronger as you beat them, you\'ll need a strong team to have the best odds of catching them': '传说宝可梦会随着你击败它们而变强，你需要一支强大的队伍才有最好的捕捉机会',
    'When enabled, automatically travels to newly unlocked locations so you can idle hands-free': '启用后自动前往新解锁的地点，让你可以完全放置',
    'When active, the battling Pokemon receives 50% EXP and all non-fainted party members receive 5% EXP each': '生效时，战斗宝可梦获得50%经验值，所有非濒死队友各获得5%经验值',
    'Click then select a pokemon to apply Honey': '点击后选择一只宝可梦使用甜甜蜜',
    'Click then select a pokemon to apply Repel': '点击后选择一只宝可梦使用除虫喷雾',
    'Applies to wild encounters and raid legendaries': '适用于野生遭遇和传说团体战',
    'Re-using on the same species extends the duration instead of stacking': '对同一物种重复使用会延长持续时间而不是堆叠',
    'All 8 Kanto gym leaders are now in the game! Defeat them in order to earn badges and progress': '关都全部8位道馆馆主现已加入游戏！按顺序击败他们获得徽章并推进进度',
    'Each gym leader has their classic team from the original games': '每位道馆馆主都拥有原作中的经典队伍',
    'Defeat all four to face Champion Blue and his full team of 6': '击败全部四位后即可挑战冠军青绿和他的6只满编队伍',
    'New Raid Island location unlocks after defeating the Champion': '击败冠军后解锁新的团体战岛地点',
    'Arrived at Raid Island! A legendary Pokemon awaits...': '到达团体战岛！一只传说宝可梦正在等待…',
    'Complete the Pokedex (catch all 151 Pokemon) to unlock the Shiny Charm': '完成宝可梦图鉴（捕捉全部151只宝可梦）即可解锁闪耀护符',
    'Check your shiny stats and charm status in the ? info menu': '在?信息菜单中查看你的闪光统计和护符状态',
    'Spend tokens in the new Reward Shop (accessible from the Gyms tab) on evolution items:': '在新的奖励商店（可通过道馆标签访问）中使用徽章购买进化道具：',
    'Earn Victory Tokens by defeating gym leaders for the first time (1 token per gym) and completing the Elite Four gauntlet (1 token per champion defeat)': '首次击败道馆馆主可获得胜利徽章（每个道馆1枚），完成四天王挑战也可获得（每次击败冠军1枚）',
    'New item available in the Reward Shop for 2 Victory Tokens': '奖励商店新增道具，售价2枚胜利徽章',
    'Pokemon that evolve by stone or trade can now be evolved using these items from the stats panel': '通过石头或交换进化的宝可梦现在可以通过属性面板使用这些道具进化',
    'Evolution button is now always visible and shows requirements, faded when not met': '进化按钮现在始终可见并显示条件，未满足时灰显',
    'Evolution items now work from the box, not just the party': '进化道具现在也能从盒子中使用，不再仅限于同行',
    'Pokemon with multiple evolution options (e.g. Eevee) show all options side by side': '有多种进化选择的宝可梦（如伊布）会同时显示所有选项',
    'Omanyte and Kabuto now evolve into Omastar and Kabutops at level 40': '菊石兽和化石盔现在在40级进化为多刺菊石兽和镰刀盔',
    'Legendary Pokemon (Articuno, Zapdos, Moltres, Mewtwo, Mew) have been removed from wild encounters': '传说宝可梦（急冻鸟、闪电鸟、火焰鸟、超梦、梦幻）已从野生遭遇中移除',
    'Starters (Bulbasaur, Charmander, Squirtle) can now be found as ultra-rare encounters in the Safari Zone': '初始宝可梦（妙蛙种子、小火龙、杰尼龟）现在可作为极度稀有遭遇在狩猎地带找到',
    'Party members can level up and learn moves from shared EXP': '队友可以从共享经验值中升级和学习招式',
    'Bag panel shows active effect status and lets you use Exp. Share directly': '背包面板显示当前效果状态，可直接使用学习装置',
    'Move manage panel now validates the active Pokemon hasn\'t changed mid-edit': '招式管理面板现在会验证当前宝可梦在编辑过程中是否已切换',
    'Active effect durations are displayed in the battle log and detail panel': '效果持续时间会显示在战斗日志和详细信息面板中',
    'Battle win tracking split into wild battles vs trainer battles, tracked per location': '战斗胜利追踪分为野生战斗和训练师战斗，按地点分别统计',
    'Completely new responsive layout for screens under 768px': '针对768px以下屏幕的全新响应式布局',
    'Tabbed navigation: Battle, Location, Party, Box, and Map tabs': '标签式导航：战斗、位置、同行、盒子和地图标签',
    'Trainer/boss sprites are larger during battle intros': '训练师/Boss精灵在战斗开场时更大',
    'Trainer name display no longer blocks buttons during trainer battles': '训练师名字显示不再遮挡训练师战斗中的按钮',
    'Fixed stretched sprites in the box, party info screen, and catch settings menu': '修复了盒子、同行信息界面和捕获设置菜单中精灵变形的问题',
    'Town map no longer shows a redundant tooltip for the current location': '城镇地图不再对当前位置显示多余的提示',
    'Growl, Leer, and Tail Whip lower the opponent\'s stats': '叫声、瞪眼和摇尾巴会降低对手的能力',
    'High Jump Kick now damages the user on a miss': '飞膝踢现在在未命中时会反伤使用者',
    'Hyper Beam now requires a recharge turn after use': '破坏光线现在使用后需要一回合蓄力',
    'Self-Destruct causes the user to faint after dealing damage': '自爆造成伤害后使用者会昏厥',
    'Recoil moves (Take Down, Submission) now deal damage back to the user': '反伤招式（猛撞、地狱翻滚）现在会对使用者造成反伤',
    'Multi-turn moves (Outrage, Petal Dance) lock the user in for 2–3 turns, then cause confusion self-damage': '多回合招式（逆鳞、花瓣舞）会锁定使用者2-3回合，然后造成混乱自伤',
    'Stat stages are factored into move selection for both sides': '能力等级变化被纳入双方招式选择考量',
    'Trainer Pokemon also weigh drawbacks when choosing moves': '训练师的宝可梦在选择招式时也会权衡副作用',
    'Stat changes range from -6 to +6 and reset each battle': '能力变化范围为-6到+6，每场战斗重置',
    'Status moves now actually work! Swords Dance, Amnesia, Barrier, Harden, Sharpen, and Defense Curl boost your stats in battle': '变化招式现在确实有效了！剑舞、瞬间失忆、屏障、变硬、棱角化和变圆可以在战斗中提升你的能力',
    'Previously all Pokemon would have full 15 IVs, now they will be randomly assigned just like in the games': '之前所有宝可梦都拥有满个体值15，现在会像原作中一样随机分配',
    'Unlock criteria reworked: routes now unlock based on battles fought at specific locations and badges earned, instead of a flat total battle count': '解锁条件重做：道路现在根据在特定地点的战斗次数和获得的徽章解锁，而非总战斗次数',
    'Route 6/Vermilion unlock order swapped with Route 7/Celadon for better progression flow': '6号道路/枯叶市解锁顺序与7号道路/玉虹市互换，以获得更好的推进节奏',
    'Safari Zone encounter weights rebalanced for smoother distribution': '狩猎地带遭遇权重重新平衡，分布更平滑',
    'As always, feedback is welcome! Join us at': '和往常一样，欢迎反馈！加入我们：',
    'Feedback is welcome! Join us at': '欢迎反馈！加入我们：',
    'to share your thoughts or report issues.': '分享你的想法或报告问题。',
    'Are you sure? This will permanently delete all save data and restart the game.': '确定要这样做吗？这将永久删除所有存档数据并重新开始游戏。',
    'New consumable items: Repel (halves encounter weight) and Honey (doubles encounter weight) for a specific Pokemon on a route, lasting 500 battles': '新增消耗道具：除虫喷雾（遭遇权重减半）和甜甜蜜（遭遇权重翻倍），对特定道路上的特定宝可梦生效，持续500场战斗',
    'Apply from the detail panel by clicking a Pokemon tile, or use the new selector mode buttons in the Wild Pokemon header to batch-apply by clicking tiles directly': '通过点击宝可梦图块在详情面板中应用，或使用野生宝可梦标题栏中的新选择模式按钮，直接点击图块批量应用',
    'Level': '等级',
    'Experience': '经验',
    'Gold': '金币',
    'Stats': '能力',
    'IV': '个体值',
    'Battle': '战斗',
    'Fight': '战斗',
    'Run': '逃跑',
    'Bag': '背包',
    'Shop': '商店',
    'Gym': '道馆',
    'Badge': '徽章',
    'Trainer': '训练师',
    'Champion': '冠军',
    'Wild': '野生',
    'Encounter': '遇敌',
    'Cave': '洞窟',
    'Starter': '初始',
    'Evolution': '进化',
    'Evolve': '进化',
    'Shiny': '闪光',
    'Raid': '团体战',
    'Legendary': '传说',
    'Auto': '自动',
    'Manual': '手动',
    'Fly': '飞翔',
    'Cut': '居合斩',
    'Strength': '怪力',
    'Flash': '闪光',
    'Bug Catcher': '捕虫少年',
    'Lass': '迷你裙',
    'Youngster': '短裤小子',
    'Hiker': '登山男',
    'Camper': '露营少年',
    'Picnicker': '野餐少女',
    'Swimmer': '泳裤小伙子',
    'Fisherman': '钓鱼人',
    'Sailor': '水手',
    'Scientist': '研究员',
    'Super Nerd': '理科男',
    'Gentleman': '绅士',
    'Beauty': '大姐姐',
    'Juggler': '杂耍艺人',
    'Tamer': '驯兽师',
    'Channeler': '祈祷师',
    'Ace Trainer': '精英训练师',
    'CoolTrainer': 'CoolTrainer',
    'Black Belt': '空手道王',
    'Rocker': '摇滚乐手',
    'Biker': '暴走族',
    'Burglar': '小偷',
    'Engineer': '工程师',
    'Gamer': '赌徒',
    'Rocket': '火箭队',
    'Pokédex': '宝可梦图鉴',
    'Pokémon': '宝可梦',
    'Current Moves': '当前招式',
    'A pitch-black cave you must navigate carefully.': '你必须小心穿越的漆黑洞窟。',
    'Atk': '攻击',
    'Def': '防御',
    'Spd': '速度',
    'hp': '生命',
    'attack': '攻击',
    'defense': '防御',
    'speed': '速度',
    'spAttack': '特攻',
    'spDefense': '特防',
    'maxHp': '最大生命',
    'normal': '一般',
    'fire': '火',
    'water': '水',
    'electric': '电',
    'grass': '草',
    'ice': '冰',
    'fighting': '格斗',
    'poison': '毒',
    'ground': '地面',
    'flying': '飞行',
    'psychic': '超能力',
    'bug': '虫',
    'rock': '岩石',
    'ghost': '幽灵',
    'dragon': '龙',
    'dark': '恶',
    'steel': '钢',
    'fairy': '妖精',
    'X': '✕',
    'ITEMS': '道具',
    'BATTLE': '战斗',
    'POKEMON': '宝可梦',
    'SETTINGS': '设置',
    'POKEDEX': '图鉴',
    'BADGES': '徽章',
    'GYMS': '道馆',
    'PARTY': '队伍',
    'BOX': '电脑',
    'MAP': '地图',
    'INFO': '信息',
    'LOG': '记录',
    'SHOP': '商店',
    'RAID': '团体战',
    'Auto Battle': '自动战斗',
    'Stop Auto': '停止自动',
    'Heal': '恢复',
    'Travel': '旅行',
    'Sell': '出售',
    'Use': '使用',
    'Equip': '装备',
    'Unequip': '卸下',
    'Filter': '筛选',
    'OK': '确定',
    'Yes': '是',
    'No': '否',
    'Delete': '删除',
    'Edit': '编辑',
    'Back': '返回',
    'Next': '下一个',
    'Prev': '上一个',
    'Close': '关闭',
    'Open': '打开',
    'Hide': '隐藏',
    'Show': '显示',
    'Reset': '重置',
    'common': '常见',
    'uncommon': '少见',
    'rare': '稀有',
    'very_rare': '非常稀有',
    'ultra_rare': '极度稀有',
    'fainted!': '倒下了！',
    'broke free!': '挣脱了！',
    'appeared!': '出现了！',
    'learned': '学会了',
    'damage!': '点伤害！',
    'was hurt by recoil!': '受到了反作用伤害！',
    'kept going and crashed!': '因惯性撞伤了！',
    'became confused and hurt itself!': '混乱中攻击了自己！',
    'evolution': '进化',
    'evolving': '进化中',
    'Healing': '恢复中',
    'healing': '恢复中',
    'Money': '金币',
    'money': '金币',
    'gold': '金币',
    'Tokens': '徽章',
    'tokens': '徽章',
    'badges': '徽章',
    'gym': '道馆',
    'Raids': '团体战',
    'raids': '团体战',
    'Dungeon': '迷宫',
    'Area': '区域',
    'Zone': '地带',
    'Floor': '层',
    'Wave': '波',
    'Round': '回合',
    'Turn': '回合',
    'Boss': '首领',
    'Enemy': '敌人',
    'Player': '玩家',
    'Ally': '队友',
    'Team': '队伍',
    'Skill': '技能',
    'Ability': '特性',
    'Passive': '被动',
    'Active': '生效中',
    'Buff': '增益',
    'Debuff': '减益',
    'Effect': '效果',
    'Status': '状态',
    'Stun': '眩晕',
    'Burn': '灼伤',
    'Freeze': '冰冻',
    'Paralyze': '麻痹',
    'Sleep': '睡眠',
    'Confuse': '混乱',
    'Curse': '诅咒',
    'Bless': '祝福',
    'physical': '物理',
    'special': '特殊',
    'status': '变化',
    'pw': '威力',
    'acc': '命中',
    'sec': '秒',
    'min': '分',
    'hour': '小时',
    'day': '天',
    'Unlocked': '已解锁',
    'Complete': '完成',
    'Incomplete': '未完成',
    'Inactive': '未激活',
    'Enabled': '已启用',
    'Disabled': '已禁用',
    'On': '开',
    'Off': '关',
    'Auto-proceed': '自动前进',
    'A small town known for Pokemon Tower.': '以宝可梦塔闻名的小镇。',
    'Route & Location Progression Overhaul': '道路 & 地点进度重制',
    'bulbasaur': '妙蛙种子',
    'ivysaur': '妙蛙草',
    'venusaur': '妙蛙花',
    'charmander': '小火龙',
    'charmeleon': '火恐龙',
    'charizard': '喷火龙',
    'squirtle': '杰尼龟',
    'wartortle': '卡咪龟',
    'blastoise': '水箭龟',
    'pikachu': '皮卡丘',
    'raichu': '雷丘',
    'mewtwo': '超梦',
    'mew': '梦幻',
    'eevee': '伊布',
    'magikarp': '鲤鱼王',
    'gyarados': '暴鲤龙',
    'ditto': '百变怪',
    'snorlax': '卡比兽',
    'dragonite': '快龙',
    'caterpie': '绿毛虫',
    'metapod': '铁甲蛹',
    'butterfree': '巴大蝶',
    'weedle': '独角虫',
    'kakuna': '铁壳蛹',
    'beedrill': '大针蜂',
    'pidgey': '波波',
    'pidgeotto': '比比鸟',
    'pidgeot': '大比鸟',
    'rattata': '小拉达',
    'raticate': '拉达',
    'spearow': '烈雀',
    'fearow': '大嘴雀',
    'ekans': '阿柏蛇',
    'arbok': '阿柏怪',
    'sandshrew': '穿山鼠',
    'sandslash': '穿山王',
    'nidoranf': '尼多兰',
    'nidorina': '尼多娜',
    'nidoqueen': '尼多后',
    'nidoranm': '尼多朗',
    'nidorino': '尼多力诺',
    'nidoking': '尼多王',
    'clefairy': '皮皮',
    'clefable': '皮可西',
    'vulpix': '六尾',
    'ninetales': '九尾',
    'jigglypuff': '胖丁',
    'wigglytuff': '胖可丁',
    'zubat': '超音蝠',
    'golbat': '大嘴蝠',
    'oddish': '走路草',
    'gloom': '臭臭花',
    'vileplume': '霸王花',
    'paras': '派拉斯',
    'parasect': '派拉斯特',
    'venonat': '毛球',
    'venomoth': '末入蛾',
    'diglett': '地鼠',
    'dugtrio': '三地鼠',
    'meowth': '喵喵',
    'persian': '猫老大',
    'psyduck': '可达鸭',
    'golduck': '哥达鸭',
    'mankey': '猴怪',
    'primeape': '火爆猴',
    'growlithe': '卡蒂狗',
    'arcanine': '风速狗',
    'poliwag': '蚊香蝌蚪',
    'poliwhirl': '蚊香君',
    'poliwrath': '蚊香泳士',
    'abra': '凯西',
    'kadabra': '勇基拉',
    'alakazam': '胡地',
    'machop': '腕力',
    'machoke': '豪力',
    'machamp': '怪力',
    'bellsprout': '喇叭芽',
    'weepinbell': '口呆花',
    'victreebel': '大食花',
    'tentacool': '玛瑙水母',
    'tentacruel': '毒刺水母',
    'geodude': '小拳石',
    'graveler': '隆隆石',
    'golem': '隆隆岩',
    'ponyta': '小火马',
    'rapidash': '烈焰马',
    'slowpoke': '呆呆兽',
    'slowbro': '呆壳兽',
    'magnemite': '小磁怪',
    'magneton': '三合一磁怪',
    'farfetchd': '大葱鸭',
    'doduo': '嘟嘟',
    'dodrio': '嘟嘟利',
    'seel': '小海狮',
    'dewgong': '白海狮',
    'grimer': '臭泥',
    'muk': '臭臭泥',
    'shellder': '大舌贝',
    'cloyster': '刺甲贝',
    'gastly': '鬼斯',
    'haunter': '鬼斯通',
    'gengar': '耿鬼',
    'onix': '大岩蛇',
    'drowzee': '催眠貘',
    'hypno': '引梦貘人',
    'krabby': '大钳蟹',
    'kingler': '巨钳蟹',
    'voltorb': '霹雳电球',
    'electrode': '顽皮雷弹',
    'exeggcute': '蛋蛋',
    'exeggutor': '椰蛋树',
    'cubone': '卡拉卡拉',
    'marowak': '嘎啦嘎啦',
    'hitmonlee': '沙瓦郎',
    'hitmonchan': '艾比郎',
    'lickitung': '大舌头',
    'koffing': '瓦斯弹',
    'weezing': '双弹瓦斯',
    'rhyhorn': '铁甲犀牛',
    'rhydon': '铁甲暴龙',
    'chansey': '吉利蛋',
    'tangela': '蔓藤怪',
    'kangaskhan': '袋兽',
    'horsea': '墨海马',
    'seadra': '海刺龙',
    'goldeen': '角金鱼',
    'seaking': '金鱼王',
    'staryu': '海星星',
    'starmie': '宝石海星',
    'mrmime': '魔墙人偶',
    'scyther': '飞天螳螂',
    'jynx': '迷唇姐',
    'electabuzz': '电击兽',
    'magmar': '鸭嘴火兽',
    'pinsir': '凯罗斯',
    'tauros': '肯泰罗',
    'lapras': '拉普拉斯',
    'vaporeon': '水伊布',
    'jolteon': '雷伊布',
    'flareon': '火伊布',
    'porygon': '多边兽',
    'omanyte': '菊石兽',
    'omastar': '多刺菊石兽',
    'kabuto': '化石盔',
    'kabutops': '镰刀盔',
    'aerodactyl': '化石翼龙',
    'articuno': '急冻鸟',
    'zapdos': '闪电鸟',
    'moltres': '火焰鸟',
    'dratini': '迷你龙',
    'dragonair': '哈克龙',
    '{{0}} took {{1}} damage!': '{{0}} 受到 {{1}} 点伤害！',
    '{{0}} fainted!': '{{0}} 倒下了！',
    '{{0}} learned {{1}}!': '{{0}} 学会了 {{1}}！',
    '{{0}} was hurt by recoil! ({{1}} damage)': '{{0}} 受到了反作用力伤害！（{{1}} 点）',
    '{{0}} broke free!': '{{0}} 挣脱了！',
    '{{0}} became confused and hurt itself! ({{1}} damage)': '{{0}} 混乱并攻击了自己！（{{1}} 点伤害）',
    '{{0}} kept going and crashed! ({{1}} damage)': '{{0}} 停不下来并撞到了！（{{1}} 点伤害）',
    '{{0}}\'s attack missed!': '{{0}} 的攻击没有命中！',
    '✦ A shiny {{0}} appeared!': '✦ 一只闪光 {{0}} 出现了！',
    '{{0}} used {{1}}!': '{{0}} 使用了 {{1}}！',
    '{{0}}\'s {{1}} sharply rose!': '{{0}} 的 {{1}} 大幅提升了！',
    '{{0}}\'s {{1}} rose!': '{{0}} 的 {{1}} 提升了！',
    '{{0}}\'s {{1}} sharply fell!': '{{0}} 的 {{1}} 大幅降低了！',
    '{{0}}\'s {{1}} fell!': '{{0}} 的 {{1}} 降低了！',
    '{{0}} is confused!': '{{0}} 混乱了！',
    '{{0}} was poisoned!': '{{0}} 中毒了！',
    '{{0}} was burned!': '{{0}} 烧伤了！',
    '{{0}} was paralyzed!': '{{0}} 麻痹了！',
    '{{0}} fell asleep!': '{{0}} 睡着了！',
    '{{0}} sent out {{1}}!': '{{0}} 派出了 {{1}}！',
    '{{0}} defeated {{1}}!': '{{0}} 打败了 {{1}}！',
    '{{0}} earned {{1}} gold!': '{{0}} 获得了 {{1}} 金币！',
    '{{0}} lost {{1}} gold!': '{{0}} 损失了 {{1}} 金币！',
    '{{0}} was caught!': '{{0}} 被捉住了！',
    '{{0}} was caught with a {{1}}!': '{{0}} 被 {{1}} 捉住了！',
    '{{0}} is evolving!': '{{0}} 正在进化！',
    '{{0}} evolved into {{1}}!': '{{0}} 进化成了 {{1}}！',
    '{{0}} grew to level {{1}}!': '{{0}} 升到了 {{1}} 级！',
    'Raid complete! {{0}} was defeated!': '团体战完成！{{0}} 被击败了！',
    'Raid failed! {{0}} fled!': '团体战失败！{{0}} 逃跑了！',
    'Lv': '等级',
    '{{0}} x {{1}}': '{{0}} × {{1}}',
    'HP: {{%d}}': '生命：{{%d}}',
    'ATK: {{%d}}': '攻击：{{%d}}',
    'DEF: {{%d}}': '防御：{{%d}}',
    'SP.A: {{%d}}': '特攻：{{%d}}',
    'SP.D: {{%d}}': '特防：{{%d}}',
    'SPD: {{%d}}': '速度：{{%d}}',
    'Pow': '威力',
    'Acc': '命中',
    'Routes:': '道路：',
    '★ Always catch shinies': '★ 总是捕捉闪光',
    'All': '全部',
    '← Back to Game': '← 返回游戏',
    'SP.A': '特攻',
    'SP.D': '特防',
    'ATK': '攻击',
    'DEF': '防御',
    'SPD': '速度',
    'Exp': '经验',
    'IVs': '个体值',
    'Lvl': '等级',
    'lvl': '等级',
    'level': '等级',
    'caught': '已捕',
    'seen': '已见',
    'total': '总计',
    'battles': '战斗',
    'Battles': '战斗',
    'wins': '胜',
    'losses': '负',
    'pokemon': '宝可梦',
    'items': '道具',
    'party': '队伍',
    'box': '电脑',
    'moves': '招式',
    'shop': '商店',
    'raid': '团体战',
    'route': '道路',
    'town': '城镇',
    'cave': '洞窟',
    'forest': '森林',
    'island': '岛',
    'city': '市',
    'wild': '野生',
    'trainer': '训练师',
    'battle': '战斗',
    'catch': '捕捉',
    'evolve': '进化',
    'shiny': '闪光',
    'stats': '能力',
    'info': '信息',
    'Hello and welcome to Pokemon Idle! Please be aware that this game is still in the very early stages of development so I welcome any and all feedback. I apologize for the lack of detailed tutorial system but I just haven\'t had a chance. Feel free to join the': '欢迎来到宝可梦放置！请注意本游戏仍处于非常早期的开发阶段，欢迎任何反馈。对于缺乏详细教程系统我深表歉意，实在是还没时间做。欢迎加入',
    'catch all 151 Pokemon to unlock the Shiny Charm (2x shiny rate)': '捕捉全部151只宝可梦以解锁闪耀护符（闪光概率翻倍）',
    'Buy them from any Poke Mart for $2,000 each': '可在任何宝可梦商店以每个$2,000的价格购买',
    'Active effects show as blue "R" and yellow "H" badges on encounter tiles': '效果激活时会在遭遇图块上显示蓝色"R"和黄色"H"徽章',
    'Lasts 1000 battles — activate from your Bag': '持续1000场战斗 — 从背包中激活',
    'Added "Ultra Rare" rarity tier for the rarest encounters': '新增"极度稀有"稀有度等级，用于最稀有的遭遇',
    'Default catch mode changed from "Always" to "Pokedex New" for less ball waste': '默认捕捉模式从"总是"改为"图鉴新"以减少精灵球浪费',
    'Duplicate move learning is now prevented — Pokemon won\'t re-learn moves they already know': '现在防止重复学习招式 — 宝可梦不会重新学习已掌握的招式',
    'Normal catch logic applies during raids — use your default ball settings': '团体战中适用普通捕捉逻辑 — 使用你的默认精灵球设置',
    '10-minute cooldown between raids, persists across refreshes': '团体战之间有10分钟冷却时间，刷新后仍然有效',
    'Your Pokemon now considers move drawbacks when picking attacks — it won\'t blindly spam Hyper Beam over Flamethrower': '你的宝可梦现在选择攻击时会权衡招式副作用 — 不会无脑地用破坏光线而不用喷射火焰',
    'After earning all 8 badges, take on the Elite Four gauntlet — Lorelei, Bruno, Agatha, and Lance back-to-back': '获得全部8枚徽章后，挑战四天王连战 — 连续对战科拿、希巴、菊子和渡',
    'Fire Stone, Water Stone, Thunder Stone, Leaf Stone — 1 token each': '火之石、水之石、雷之石、叶之石 — 各1枚徽章',
    'Moon Stone, Link Cable — 2 tokens each': '月之石、连接线 — 各2枚徽章',
    'New toggle button (▶▶) next to the settings gear in the battle scene': '战斗场景中设置齿轮旁边新增切换按钮（▶▶）',
    'experience': '经验',
    '+ HEAL': '+ 恢复',
    'Pokedex:': '宝可梦图鉴：',
    'Map': '地图',
    'Progress': '进度',
    'Variants': '变体',
    'Lifeskill': '生活技能',
    'Crafting': '制作',
    'READY': '就绪',
    'always': '总是',
    'shiny_only': '仅闪光',
    'pokedex_new': '图鉴新',
    'level_threshold': '等级阈值',
    'You chose {{0}}!': '你选择了 {{0}}！',
    'Traveled to {{0}}!': '前往了 {{0}}！',
    'Wild {{0}} appeared!': '野生 {{0}} 出现了！',
    '{{0}}W {{1}}T': '{{0}}胜 {{1}}训练师',
    'Battles at {{0}}': '在{{0}}的战斗',
    '{{0}}/3 battles at {{1}}': '{{0}}/3 场在{{1}}的战斗',
    '{{0}}/{{1}} battles at {{2}}': '{{0}}/{{1}} 场在{{2}}的战斗',
    '{{0}}W {{1}}L': '{{0}}胜 {{1}}负',
    'viridian city': '常青市',
    'viridian forest': '常青森林',
    'pewter city': '深灰市',
    'cerulean city': '华蓝市',
    'vermilion city': '枯叶市',
    'lavender town': '紫苑镇',
    'celadon city': '彩虹市',
    'fuchsia city': '浅红市',
    'saffron city': '金黄市',
    'cinnabar island': '红莲岛',
    'indigo plateau': '石英高原',
    'mt. moon': '月见山',
    'rock tunnel': '岩山隧道',
    'safari zone': '狩猎地带',
    'seafoam islands': '双子岛',
    'victory road': '冠军之路',
    'power plant': '无人发电厂',
    'pokemon tower': '宝可梦塔',
    'pokemon mansion': '宝可梦大宅',
    'diglett\'s cave': '地鼠洞窟',
    'cerulean cave': '华蓝洞窟',
    'route 1': '1号道路',
    'route 2': '2号道路',
    'route 3': '3号道路',
    'route 4': '4号道路',
    'route 5': '5号道路',
    'route 6': '6号道路',
    'route 7': '7号道路',
    'route 8': '8号道路',
    'route 9': '9号道路',
    'route 10': '10号道路',
    'route 11': '11号道路',
    'route 12': '12号道路',
    'route 13': '13号道路',
    'route 14': '14号道路',
    'route 15': '15号道路',
    'route 16': '16号道路',
    'route 17': '17号道路',
    'route 18': '18号道路',
    'route 19': '19号道路',
    'route 20': '20号道路',
    'route 21': '21号道路',
    'route 22': '22号道路',
    'route 23': '23号道路',
    'route 24': '24号道路',
    'route 25': '25号道路',
    'celadon dept. store': '彩虹百货公司',
    'nugget bridge': '金珠大桥',
    'cerulean mart': '华蓝友好商店',
    'cinnabar mart': '红莲友好商店',
    'fuchsia mart': '浅红友好商店',
    'indigo plateau mart': '石英友好商店',
    'lavender mart': '紫苑友好商店',
    'pewter mart': '深灰友好商店',
    'saffron mart': '金黄友好商店',
    'vermilion mart': '枯叶友好商店',
    'viridian mart': '常青友好商店',
    '! Added to party.': '！已加入队伍。',
    '! Sent to box.': '！已存入电脑。',
    'Congratulations!': '恭喜！',
    'Traveled to': '前往了',
    'You returned to': '你回到了',
    'for winning!': '，胜利奖励！',
    'evolved into': '进化成了',
    'is evolving!': '正在进化！',
    'Use Honey (x': '使用甜甜蜜（x',
    'Use Repel (x': '使用除虫喷雾（x',
    '{{0}}! Added to party.': '{{0}}！已加入队伍。',
    '{{0}}! Sent to box.': '{{0}}！已存入电脑。',
    'Congratulations! You defeated {{0}}!': '恭喜！你打败了 {{0}}！',
    'Use Honey (x{{0}})': '使用甜甜蜜（x{{0}}）',
    'Use Repel (x{{0}})': '使用除虫喷雾（x{{0}}）',
    'You returned to {{0}}.': '你回到了 {{0}}。',
    '{{0}} for winning!': '{{0}}，胜利奖励！',
    'Defeated {{0}}!': '打败了 {{0}}！',
    '{{0}} was released.': '{{0}} 被放生了。',
    'Unseen': '未见过',
    'unseen': '未见过',
    'Caught': '捉到了',
    'Seen': '已见过',
    'New': '新',
    'new': '新',
    'Amount': '数量',
    'Price': '价格',
    'Owned': '持有',
    'Remaining': '剩余',
    'encounters': '遇敌',
    'species': '物种',
    'Total': '总计',
    'Wins': '胜',
    'Losses': '负',
    'Fainted': '濒死',
    'fainted': '濒死',
    'Healthy': '健康',
    'Done': '完成',
    'Name': '名称',
    'Type': '属性',
    'Power': '威力',
    'Accuracy': '命中',
    'Category': '类别',
    'token': '徽章',
    'Coins': '金币',
    'coins': '金币',
    'Price:': '价格：',
    'Cost:': '花费：',
    '{{0}} wants to battle!': '{{0}} 发起了挑战！',
    '{{0}} is about to send out {{1}}!': '{{0}} 即将派出 {{1}}！',
    '{{0}} gained {{1}} EXP!': '{{0}} 获得了 {{1}} 经验值！',
    'Go! {{0}}!': '上吧！{{0}}！',
    'Got {{0}} for winning!': '获得了 {{0}}，胜利奖励！',
    'Got': '获得了',
    'Picnicker Lola': '野餐少女 萝拉',
    'Leader Brock': '馆主 小刚',
    'Leader Misty': '馆主 小霞',
    'Leader Lt. Surge': '馆主 马志士',
    'Leader Erika': '馆主 莉佳',
    'Leader Koga': '馆主 阿桔',
    'Leader Sabrina': '馆主 娜姿',
    'Leader Blaine': '馆主 夏伯',
    'Leader Giovanni': '馆主 坂木',
    'Elite Four Lorelei': '四天王 科拿',
    'Elite Four Bruno': '四天王 希巴',
    'Elite Four Agatha': '四天王 菊子',
    'Elite Four Lance': '四天王 渡',
    'Champion Blue': '冠军 青绿',
    'Solar Beam': '日光束',
    'Double-Edge': '舍身冲撞',
    'Thunder': '打雷',
    'Recover': '自我再生',
    'Soft-Boiled': '生蛋',
    'Stun Spore': '麻痹粉',
    'Spore': '蘑菇孢子',
    'Growth': '生长',
    'Double Team': '影子分身',
    'Minimize': '变小',
    'Metronome': '挥指',
    'Transform': '变身',
    'Explosion': '大爆炸',
    'Thrash': '大闹一番',
    'Waterfall': '攀瀑',
    'Magical Leaf': '魔法叶',
    'Go!': '上吧！',
    'Dollar': '元',
    'dollars': '元',
    'Caught {{0}}!': '捉到了 {{0}}！',
    'Caught {{0}}! Added to party.': '捉到了 {{0}}！已加入队伍。',
    'Caught {{0}}! Sent to box.': '捉到了 {{0}}！已存入电脑。',
    '{{0}} is now accessible!': '{{0}} 现在可以前往了！',
    'is now accessible!': '现在可以前往了！',
    '{{0}} fled!': '{{0}} 逃跑了！',
    '{{0}} escaped!': '{{0}} 逃脱了！',
    '{{0}} is fast asleep.': '{{0}} 睡得很香。',
    '{{0}} is paralyzed! It can\'t move!': '{{0}} 麻痹了！无法行动！',
    '{{0}} hurt itself in confusion!': '{{0}} 在混乱中攻击了自己！',
    '{{0}} snapped out of confusion!': '{{0}} 从混乱中清醒了！',
    '{{0}}\'s status cleared!': '{{0}} 的状态恢复了！',
};

// ============================================================
// cnResourceNames — 资源名词翻译（处理 "Label: value" 格式）
// ============================================================
var cnResourceNames = {
    'HP': '生命',
    'hp': '生命',
    'Attack': '攻击',
    'attack': '攻击',
    'Atk': '攻击',
    'ATK': '攻击',
    'Defense': '防御',
    'defense': '防御',
    'Def': '防御',
    'DEF': '防御',
    'Sp. Atk': '特攻',
    'Sp.A': '特攻',
    'SpA': '特攻',
    'SP.A': '特攻',
    'Sp. Def': '特防',
    'Sp.D': '特防',
    'SpD': '特防',
    'SP.D': '特防',
    'Speed': '速度',
    'speed': '速度',
    'Spd': '速度',
    'SPD': '速度',
    'Level': '等级',
    'level': '等级',
    'Lv': '等级',
    'Experience': '经验',
    'EXP': '经验',
    'Exp': '经验',
    'Gold': '金币',
    'gold': '金币',
    'Money': '金币',
    'Power': '威力',
    'Accuracy': '命中',
    'Category': '类别',
    'Type': '属性',
    'Status': '状态',
    'Effect': '效果',
    'Price': '价格',
    'Cost': '花费',
    'Amount': '数量',
    'Owned': '持有',
    'Active': '生效中',
    'Battles': '战斗',
    'Wins': '胜',
    'Losses': '负',
    'Caught': '已捕',
    'Seen': '已见',
    'Total': '总计',
    'Remaining': '剩余',
    'Tokens': '徽章',
};

// ============================================================
// cnRegReplace — 正则替换（仅处理模板无法覆盖的特殊格式）
// ============================================================
// 注意：动态消息全部由 cnItems 模板({{0}})处理（支持递归翻译）
var cnRegReplace = new Map([
    // 仅保留纯格式替换（无需递归翻译捕获值）
    [/^₽([\d,]+)$/, '₽$1'],
]);

// ============================================================
// 前缀/后缀提取
// ============================================================
var cnPrefix = {
    ': ': '：',
};
var cnPostfix = {
    ':': '：',
};

// ============================================================
// 排除规则
// ============================================================
var cnExcludeWhole = [];
var cnExcludePostfix = [];